services:
  web_local:
    profiles:
      - local
    build: .
    environment:
      - DEBUG=True

  web_prod:
    profiles:
      - prod
    image: registry.gitlab.com/internship4450447/ci_cd_traefik
    environment:
      - DEBUG=True
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_prod.entrypoints=http"
      - "traefik.http.routers.web_prod.rule=Host(`ankoay.farmasia.tech`)"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.web_prod.middlewares=redirect-to-https"
      - "traefik.http.routers.web_prod-secure.entrypoints=https"
      - "traefik.http.routers.web_prod-secure.rule=Host(`ankoay.farmasia.tech`)"
      - "traefik.http.routers.web_prod-secure.tls=true"
      - "traefik.http.routers.web_prod-secure.tls.certresolver=http"
      - "traefik.http.services.web_prod.loadbalancer.server.port=8000"


networks:
  proxy:
    external: true
