name: Docker Build & Push

on:
  push:
    paths:
      - "website/**"
      - "docker-compose.yaml"
      - ".github/workflows/docker-ci.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ankoayfeno/chronoci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./website
          file: website/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}
          no-cache: true
